language: cpp
dist: xenial
sudo: false
compiler: gcc

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      os: linux
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      os: osx

script: cmake . && make && ctest -VV
