language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - build-essential
            - cmake
            - libboost-all-dev
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      os: osx
      compiler: gcc


script: cmake . && make && make test
