language: cpp
dist: trusty
sudo: true
compiler: gcc

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      os: linux
      addons:
        apt:
          update: true
          packages:
            - build-essential
            - cmake
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      os: osx
      addons:
        homebrew:
          update: true
          packages:
            - cmake


script: cmake . && make && sudo make test
